### ISSUE TITLE
[Feature Request] Graph Time

### ISSUE THREAD

**Issue by nsde** [ToBiDi0410/SpigotDash#10]
Please add a GUI option in the dashboard to change the graph time (see below) from 10 minutes to other values, e.g. 1 hour or 30 minutes.

I'm not completely sure, but I think this is the line for that:
https://github.com/ToBiDi0410/SpigotDash/blob/bd5e7fd469ac50ea85eb69e743d17d8097c79404/src/main/java/de/tobias/spigotdash/utils/taskManager.java#L78

![image](https://user-images.githubusercontent.com/67185896/152699292-53b4f466-8810-4d1c-9701-3c6578a5f2d9.png)

**Comment by ToBiDi0410** [comment]
This should be possible easily will look at that soon. I took a "break" for a long time now, but I think I will have time just tomorrow.

**Comment by ToBiDi0410** [comment]
I will probably use the zoom options of the Graphs and just store more data

**Comment by ToBiDi0410** [comment]
Should be done with this commit: https://github.com/ToBiDi0410/SpigotDash/commit/159bf41f47f4ce13d5ffc32162d61321f5e13b54
_If not, please reopen this issue!_ 
**_Thank you <3_**
