### ISSUE TITLE
[Feature Request] Permission groups

### ISSUE THREAD

**Issue by nsde** [ToBiDi0410/SpigotDash#12]
I would love to see a feature to add new user passwords/logins and permission groups/"roles" to users.

Please add the ability to configure permission groups/roles, just like so:

- [ ] Can view files
- [ ] Can stop server
- [ ] Can view console
- [ ] Can reload server
- [ ] Can modify plugins
- [ ] Can change whitelist
- [ ] Can disable Nether/End
- [ ] Can change player OP status
- [ ] Can run commands in console
- [ ] Can change world time and weather 
- [ ] ...

And pre-made roles:
- Owner ⭐ 
  - All permissions & can change other user's dashboard permissions
- Admin 🔒 
  - All permissions
- Operator 🔧 
  - Moderator, *plus* plugin & server reloading 
- Moderator 👮 
  - Everything except: files, stopping/reloading the server, plugins, console
- Viewer 👁️ 
  - Can see everything, but can't click any buttons/change options (e.g. time/world/etc.)
- Default 👋 
  - Can see (but not edit) Graphs, Worlds, Players

**Comment by nsde** [comment]
Ich merke gerade, dass das schon mit #3 eingeführt wurde, also nevermind.
I just noticed that this already was implemented with #3, so nevermind.

**Comment by ToBiDi0410** [comment]
Default groups could be added, tho. But I think this is not necessary.

**Comment by ToBiDi0410** [comment]
And the Players Actions, as well as World Action currently don't have any permissions (I think)
