### ISSUE TITLE
Add Implementation to NuVotifier

### ISSUE THREAD

**Issue by ToBiDi0410** [ToBiDi0410/SpigotDash#4]

**Comment by IuCC123** [comment]
> Currently, I can't find any documentation of the API for this Plugin. This would require some work to find out.
> 
> _**This Issue is not closed, but it's ranked behind other issues because it needs too much work or is currently not possible to realize!**_

I found this for you: https://github.com/NuVotifier/NuVotifier/wiki

**Comment by ToBiDi0410** [comment]
Might look at this today

**Comment by ToBiDi0410** [comment]
Will close this because of the low demand.
